#!/bin/bash
set -x
show_help() {
  cat <<EOF
Usage: goshy [Options] FILE
Options:
  -b --burn              Burn after reading.
  -h --help              Print this help message.
  -u --only--url         Print only URL as response.
  -p --period TIMEFRAME  Set a custom expiry period.
EOF
}

while getopts p:period: flag
do
  case "$\{flag\}" in
    p) PERIOD_IS_SET=1;;
    period) PERIOD_IS_SET=1;;
  esac
done > /dev/null 2>&1

if [ -z $PERIOD_IS_SET ]; then
  PERIOD='3d'
fi

while :; do
  case "$1" in
    -p|--period)
      PERIOD=$2
      shift
      ;;

    -b|--burn)
      BURN='-F burn=1'
      ;;

    -u|--only-url)
      ONLYURL='?onlyURL'
      ;;

    -h|--help)
      show_help
      exit 0
      ;;

    *)
      FILE=$1
      break
  esac

  shift
done

PERIOD="-F period=$PERIOD"

if [[ -z "$1" ]]; then
  show_help
  exit 1
fi

curl $GOSH_INSTANCE/$ONLYURL -F "file=@$1" $PERIOD $BURN 
