#!/usr/bin/env bash

show_help() {
  cat <<EOF
Usage: goshy [Options] FILE
Options:
  -b --burn              Burn after reading.
  -h --help              Print this help message.
  -u --only-url          Print only URL as response.
  -p --period TIMEFRAME  Set a custom expiry period.
EOF
}

while :; do
  case "$1" in
    -p|--period)
      PERIOD="-F time=$2"
      shift
      ;;

    -b|--burn)
      BURN="-F burn=1"
      ;;

    -u|--only-url)
      ONLYURL="?onlyURL"
      ;;

    -h|--help)
      show_help
      exit 0
      ;;

    *)
      FILE=$1
      break
  esac

  shift
done

if [[ -z "$1" ]]; then
  show_help
  exit 1
fi

curl "${GOSH_INSTANCE}/${ONLYURL}" -F "file=@${FILE}" $PERIOD $BURN
