# Default values for gosh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
user: "_gosh"
group: "_gosh"

store:
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 25Gi
    annotations: {}

  path: "./store"
  id_generator:
    type: "random"
    length: 8
    # Uncomment the line below if using a wordlist file
    # file: "/usr/share/dict/words"

webserver:
  listen:
    protocol: "tcp"
    bound: ":8080"
  unix_socket:
    chmod: "0600"
    owner: "www"
    group: "www"
  protocol: "http"
  url_prefix: ""
  static_files:
    favicon:
      path: "/path/to/favicon.ico"
      mime: "image/vnd.microsoft.icon"
    custom_css:
      path: "/path/to/custom.css"
      mime: "text/css"
  item_config:
    max_size: "10MiB"
    max_lifetime: "24h"
    mime_drop:
      - "application/vnd.microsoft.portable-executable"
      - "application/x-msdownload"
    mime_map:
      "text/html": "text/plain"
  contact: "nobody@example.com"


replicaCount: 1

image:
  repository: docker.io/rehwanne/gosh
  #pullPolicy: IfNotPresent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
  hosts: []
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
